# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev_hello_world',
                'doc_host': 'https://tixel.github.io',
                'git_url': 'https://github.com/tixel/nbdev_hello_world',
                'lib_path': 'nbdev_hello_world'},
  'syms': {'nbdev_hello_world.core': {'nbdev_hello_world.core.foo': ('core.html#foo', 'nbdev_hello_world/core.py')}}}
